# This workflow will release a package at npmjs and at GitHub releases

name: Release

on:
  push:
    tags:
      - v*

jobs:
  npm:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org/
    - name: Install and build
      run: |
        npm ci
        npm run build
    - name: Publish to npm
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  github:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install, build, and pack
      run: |
        npm ci
        npm run build
        npm pack
    - run: |
        echo "ARTIFACT_NAME=$(ls gbv-login-client-*.tgz)" >> $GITHUB_ENV
    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: login-client ${{ github.ref }}
        body: TODO
        draft: true
        prerelease: false
    - name: Upload asset to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.ARTIFACT_NAME }}
        asset_name: ${{ env.ARTIFACT_NAME }}
        asset_content_type: application/gzip
